// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main (
 output v03f209,
 output v8d7e71,
 output [0:5] vinit
);
 wire w0;
 wire w1;
 assign v03f209 = w0;
 assign v8d7e71 = w1;
 vfebcfe vf92c83 (
  .v9fb85f(w0)
 );
 vfebcfe v4f2ed8 (
  .v9fb85f(w1)
 );
 assign vinit = 6'b000000;
endmodule

//---------------------------------------------------
//-- Led on
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
